# Generated by Django 5.2.5 on 2025-08-15 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Categorías",
            },
        ),
        migrations.CreateModel(
            name="Ubicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ciudad", models.CharField(max_length=100)),
                ("pais", models.CharField(default="Colombia", max_length=100)),
            ],
            options={
                "verbose_name_plural": "Ubicaciones",
            },
        ),
        migrations.CreateModel(
            name="Empleo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("empresa", models.CharField(max_length=150)),
                ("descripcion", models.TextField()),
                (
                    "tipo_empleo",
                    models.CharField(
                        choices=[
                            ("full-time", "Tiempo Completo"),
                            ("part-time", "Medio Tiempo"),
                            ("contract", "Contrato"),
                            ("remote", "Remoto"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "salario_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "salario_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("email_contacto", models.EmailField(max_length=254)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empleos.categoria",
                    ),
                ),
                (
                    "ubicacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empleos.ubicacion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
